"""adding mbid to record table

Revision ID: 467ac43ac9ba
Revises: 9147aa6b35f2
Create Date: 2018-09-26 20:14:13.023933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467ac43ac9ba'
down_revision = '9147aa6b35f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('mbid', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_record_mbid'), 'record', ['mbid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_mbid'), table_name='record')
    op.drop_column('record', 'mbid')
    # ### end Alembic commands ###
