"""adding link to user and record

Revision ID: 9b55119aed77
Revises: 50223be9d465
Create Date: 2018-08-28 20:53:17.858083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b55119aed77'
down_revision = '50223be9d465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'record', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_column('record', 'user_id')
    # ### end Alembic commands ###
